# List of commit statuses that must pass on the merge commit before it is pushed to master.
status = [
  "Tests result",
  "Rustsec Audit",
]
# If set to true, and if the PR branch is on the same repository that bors-ng itself is on, the branch will be deleted.
delete_merged_branches = true
