[package]
name = "serde_with_macros"
version = "1.0.0"
authors = ["jonasbb"]

description = "proc-macro library for serde_with"
documentation = "https://docs.rs/serde_with_macros/"
repository = "https://github.com/jonasbb/serde_with/serde_with_macros"
readme = "README.md"
keywords = ["serde", "utilities", "serialization", "deserialization"]
license = "MIT/Apache-2.0"

[lib]
proc-macro = true

[badges]
travis-ci = { repository = "jonasbb/serde_with", branch = "master" }
codecov = { repository = "jonasbb/serde_with", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
proc-macro2 = { version = "0.4.27" }
quote = "0.6.11"

[dependencies.syn]
version = "0.15.29"
features = [
    # "extra-traits", # Only for debugging
    "full",
]

[dev-dependencies]
pretty_assertions = "0.5.1"
serde = { version = "1.0.75", features = [ "derive" ] }
serde_json = "1.0.25"
version-sync = "0.7.0"

[package.metadata.docs.rs]
all-features = true
